### ISSUE TITLE
Error creating quizzes

### ISSUE THREAD

**Issue by elimisteve** [phrazzld/studymode#3]
I put in a link to https://en.wikipedia.org/wiki/Stoicism but apparently I had to specify JSON:

![studymode-creatingquiz-error-Screenshot_2023-02-12_21-17-31](https://user-images.githubusercontent.com/139603/218376661-50f256da-07d3-4210-bc73-3f09dca4f398.png)

**Comment by moomooskycow** [comment]
I'll take a closer look at this one, but it's definitely an unclear UX issue on our side -- the current quiz creation flow wants text pasted in, rather than a URL. We can make that clearer.

We're exploring content generation by phrase too (e.g. entering "Stoic philosophers" should write the study materials for you and generate quizzes from that), as well as supporting arbitrarily long sources (tougher nut to crack).

Technically though I'm not sure why this would outright fail rather than just create a weird bad quiz. You aren't required to input JSON, but GPT returns the quizzes it produces from your input in JSON. I'll see if I can reproduce, but the probabilistic nature of programming LLM interfaces makes that ... occasionally challenging, haha.

We can probably, at the very least, validate that the generated quizzes are in proper JSON format and, if they aren't, show a user-friendly error message.
